<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>UFOps.Foundation.Storage</AssemblyName>
    <RootNamespace>UFOps.Foundation.Storage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="../UFOps.Core/UFOps.Core.csproj" />
  </ItemGroup>
</Project>
