<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>UFOps.EngineSdk</AssemblyName>
    <RootNamespace>UFOps.EngineSdk</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UFOps.Core/UFOps.Core.csproj" />
  </ItemGroup>
</Project>
